task3
par5ifal1/csad2425ki401demchukdp05 pull request #3
Opened 2024-11-17 19:41 UTC by par5ifal1

2024-11-17 20:56 UTC, PavloFedakNULP requested changes

2024-11-17 20:56 UTC, PavloFedakNULP commented on src/task3.ino
> +  }
1. Розбити на менші методи
2. Спростити де можливо

2024-11-17 20:56 UTC, PavloFedakNULP commented on src/task3.ino
> +}
1. Розбити на менші методи
2. Спростити де можливо

2024-11-17 22:00 UTC, par5ifal1 commented on src/task3.ino
> +}
Виправив

2024-11-18 17:03 UTC, PavloFedakNULP approved these changes

2024-11-18 19:22 UTC, merged